options:
  logging: CLOUD_LOGGING_ONLY # Sends logs only to Cloud Logging

steps:
  # Reservation
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '-t', # Fixing the missing dash before 't'
        'europe-central2-docker.pkg.dev/sleepr-448909/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-central2-docker.pkg.dev/sleepr-448909/reservations/production',
      ]

  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-448909/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'europe-central2-docker.pkg.dev/sleepr-448909/auth/production']

  # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-448909/notifications/production',
        '-f',
        'apps/notification/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-central2-docker.pkg.dev/sleepr-448909/notifications/production',
      ]

  # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-central2-docker.pkg.dev/sleepr-448909/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-central2-docker.pkg.dev/sleepr-448909/payments/production',
      ]
